// Default initial state for store supply
export const initialStoreSupplyState = {
    adManagement: {
      IsInstallmentBillingEnabled: false,
      IsMultiplePubsEnabled: true,
      IsDefaultToGrossRateCardEnabled: false,
      IsSurchargesEnabled: true,
      AllowNetAdjustments: true,
      AllowProductionCharges: true,
      IsSharedJobJacketEnabled: true,
      IsTextImageEnabled: true,
      IssueYearCheckBoxEnd: 12,
      IssueYearCheckBoxStart: 2022,
      IsMoveContractsEnabled: true,
      IsContactReqFieldsEnabled: true,
      CheckCreditLimitOnRunsheet: true,
      CheckCreditLimitOnRunsheetDays: 30,
      CheckCreditLimitOnPropose: true,
      CheckCreditLimitOnProposeDays: 2,
      CheckCreditLimitOnAdd: true,
      CheckCreditLimitOnAddDays: 2,
      LoggedInRepChoiceProposal: true,
      LoggedInRepChoice: true,
      InvPropCheck: true,
      StopInvPropFail: true,
      InvCheck: true,
      StopInvFail: true,
      IsShowAmountOnInventoryReport: true,
      PickupFrom1: "ISNULL(gsPublications.PubName,'')",
      PickupFromTextSeparator1: "','",
      PickupFrom2: "ISNULL(tblMagFrequency.IssueName,'')",
      PickupFromTextSeparator2: "','",
      PickupFrom3: "ISNULL(tblMagFrequency.IssueYear,'')",
      PickupFromTextSeparator3: "','",
      PickupFrom4: "ISNULL(tblMagFrequency.IssueMonth,'')",
      PickupFromTextSeparator4: "','",
      PickupFrom5: "ISNULL(gsContracts.AdName,'')",
      IsESignature: false,
      RsKey: "",
      IsEnableBatchOrderUpdate: true,
      IsGroupBuyEnabled: true,
      IsSubscriptionEnabled: false,
      AllowLevelPricingForMultipleProduct: false,
      IsOrderEntryByBusinessUnit: false,
      IsProposalPageLinkOppEnabled: true,
      IsProposalPageLinkRequireOppEnabled: false,
      IsEmergencyBackUpEnabled: true,
      IsInternalApprovalEnabled: false,
      IsSplitRepChangeOrder: false,
      IsChargebriteMediaOrderEnabled: false,
      CaptureCCProfileOnProposalApproval: true,
    },
  
    accountReceivable: {
      barterTradeDisplayName: "", // Add this property
      void_invoices_admin_only: false,
      consolidate_invoices_by_default: false,
      statements_per_billing_contact: false,
      allow_magazine_dropdown_in_statement: false,
      email_from_marketing_manager: false,
      allow_invoice_pdf_as_attachment: false,
      finance_charges: false,
      payment_plans: false,
      enable_schedule_invoices: false,
      enable_schedule_payments: false,
      allow_quickbooks_xero_integration: false,
      enable_multicurrency_to_quickbooks_xero: false,
      quickbooksXeroType: "",
    },
  
    account: {
      BarterDisplayName: "Trade",
      InvoiceVoidAdminOnly: true,
      CInvoiceByDefault: true,
      StatementsPerBillingContact: false,
      IsMagazineVisible: true,
      IsMirabelEmailTransSendEnabled: true,
      IsFinanceChargesEnabled: true,
      IsPaymentPlanEnabled: true,
      IsARScheduleInvoiceEnabled: false,
      IsARSchedulePaymentEnabled: false,
      IsQBIntegrationEnabled: true,
      QBIntegrationType: 5,
      IsEnableQBMultiCurrency: true,
      IsIndesignEnabled: true,
      IsFileRenameEnabled: false,
      IsSingleAdIndesignEnabled: true,
      SubscriptionTypeID: 4,
      AllowEditAdNumber: true,
      IsCallDispositionEnabled: true,
      IsStateAsTextBox: false,
      IsEnablePrimaryContactSwitch: true,
      IsEnablePrimaryContactSwitchForAdminOnly: true,
      SwitchProposals: false,
      SwitchOrders: false,
      SwitchInvoices: false,
      SwitchPaymentPlan: true,
      IsBillingContactRemoveEnabled: true,
      CanAdminOnlyRemoveBillingContact: true,
      SwitchProposalsOnBCR: false,
      SwitchOrdersOnBCR: true,
      SwitchInvoicesOnBCR: false,
      SwitchPaymentPlansOnBCR: false,
      LimitCustomerSearchByRep: false,
      LimitCustomerAddByRep: false,
      LimitCalendarByRep: false,
      AllowNonAdminAddToCalendar: true,
      IsOrderListSecurityEnabled: true,
      IsMarketingManagerNotifications: false,
      IsBCCEmailFeatureEnabled: false,
      IsSummaryEmailNotifications: false,
      IsTrackingCodeEnabled: true,
      IsRepNotificationsEnabled: false,
      CampaignerUserID: "",
      CampaignerPwd: "",
      MirabelEmailAccountId: "d3salesdemo|flipandshare.com",
      MailChimpAPIKey: "0f47d512feac3db5a43b72fec2413411-us14",
      IsEmailIDVerificationEnabled: true,
      ClientID:
        "916381401103-15lvfk9enhph9c6slrntubhk4l25j056.apps.googleusercontent.com",
      ClientSecret: "22QEsqFvtEjiEV1EDLoT9RC9",
      RedirectURI: "",
  
      PackageTypeID: 5,
      DataPackTypeID: 1,
      NumberOfDataPacks: 0,
      NumberOfAssignedDataPacks: 18,
      IsTicketEnabled: true,
      IsChatEnabled: true,
      IsOpenAIEnabled: true,
      NoteSummary: true,
      GenAIwithSalesLetter: true,
      CompanyExecutiveSummary: true,
      MeetingScheduler: true,
      AITextImprover: true,
      IsEnableMediaKitAI: true,
    },
    production: {
      digitalStudio: false,
      enableProject: false,
    },
    contact: {
      allowJobEdit: false,
      callDisposition: false,
      displayReport: false,
      primaryContactSwitch: false,
      billingContact: false,
      enableCloud: false,
    },
    customerPortal: {
      enable: false,
    },
    userSettings: {
      restrictCustomerSearch: false,
      restrictCalendar: false,
      restrictProduct: false,
      enableEmailCapture: false,
      summaryEmail: false,
      marketingManager: false,
      repNotifications: false,
    },
    communications: {
      campaign: false,
      mailingManager: false,
      mailer: false,
      enableHelpdesk: false,
    },
    googleCalendar: {
      enable: false,
      apiKey: "",
    },
    helpdesk: {
      enable: false,
    },
    mediaMailKit: {
      sendLead: false,
      sendAd: false,
      sendEmail: false,
      enableKit: false,
    },
  };