/**
 * Reports data and configuration
 */
export const reportsData = {
  Categories: [
    {
      Id: "6853ce0a6c39c0df640c5bff",
      CategoryName: "All",
    },
    {
      Id: "6853ce0a6c39c0df640c5c00",
      CategoryName: "Favorites",
    },
    {
      Id: "6853ce0a6c39c0df640c5c01",
      CategoryName: "Revenue Reports",
    },
    {
      Id: "6853ce0a6c39c0df640c5c02",
      CategoryName: "Subscribers",
    },
    {
      Id: "6853ce0a6c39c0df640c5c03",
      CategoryName: "Subscriber Reports",
    },
    {
      Id: "6853ce0a6c39c0df640c5c04",
      CategoryName: "Performance Reports",
    },
  ],
  Reports: [
    {
      Id: "6853ce5a6c39c0df640c5c05",
      Icon: "📈",
      Title: "Renewal Performance Report",
      Description:
        "Comprehensive renewal metrics including rates, trends, and campaign performance.",
      Tags: ["renewal", "performance"],
      Category: ["All", "Revenue Reports", "Performance Reports"],
      RoutePath: "/reports/renewal-performance",
      IsStarred: true,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 1,
    },
    {
      Id: "6853ce5a6c39c0df640c5c06",
      Icon: "👥",
      Title: "Active Subscriber Summary Report",
      Description:
        "Provides an overview of currently active subscribers across all products.",
      Tags: ["active", "subscribers"],
      Category: ["All", "Subscribers", "Subscriber Reports"],
      RoutePath: "/reports/active-subscriber-summary",
      IsStarred: false,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 2,
    },
    {
      Id: "6853ce5a6c39c0df640c5c07",
      Icon: "📊",
      Title: "Subscriber Demographic Report",
      Description:
        "Analyzes subscriber demographics including age, location, and subscription preferences.",
      Tags: ["demographic", "age"],
      Category: ["All", "Subscribers", "Subscriber Reports"],
      RoutePath: "/reports/subscriber-demographic",
      IsStarred: false,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 3,
    },
    {
      Id: "6853ce5a6c39c0df640c5c08",
      Icon: "��",
      Title: "Subscriber Growth Over Time Report",
      Description:
        "Shows trends in subscriber acquisition and growth patterns over time.",
      Tags: ["growth", "trends"],
      Category: ["All", "Subscribers", "Performance Reports"],
      RoutePath: "/reports/subscriber-growth-time",
      IsStarred: false,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 4,
    },
    {
      Id: "6853ce5a6c39c0df640c5c09",
      Icon: "🗺️",
      Title: "Geographic Distribution Report",
      Description:
        "Maps subscriber distribution across different geographic regions.",
      Tags: ["geographic", "distribution"],
      Category: ["All", "Subscriber Reports"],
      RoutePath: "/reports/geographic-distribution",
      IsStarred: false,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 5,
    },
    {
      Id: "6853ce5a6c39c0df640c5c0a",
      Icon: "📉",
      Title: "Churn & Cancellation Report",
      Description:
        "Tracks subscription cancellations and analyzes churn patterns.",
      Tags: ["churn", "cancellation"],
      Category: ["All", "Performance Reports"],
      RoutePath: "/reports/churn-cancellation",
      IsStarred: true,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 6,
    },
    {
      Id: "6853ce5a6c39c0df640c5c0b",
      Icon: "🎁",
      Title: "Complimentary Subscriptions Report",
      Description:
        "Reports on free subscriptions provided to staff, partners, or promotional purposes.",
      Tags: ["complimentary", "free"],
      Category: ["All", "Subscribers"],
      RoutePath: "/reports/complimentary-subscriptions",
      IsStarred: false,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 7,
    },
    {
      Id: "6853ce5a6c39c0df640c5c0c",
      Icon: "🎁",
      Title: "Gift Subscriptions Report",
      Description: "Tracks gift subscriptions given by customers to others.",
      Tags: ["gift", "subscriptions"],
      Category: ["All", "Subscribers", "Revenue Reports"],
      RoutePath: "/reports/gift-subscriptions",
      IsStarred: false,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 8,
    },
    {
      Id: "6853ce5a6c39c0df640c5c0d",
      Icon: "⏰",
      Title: "Subscription Aging Report",
      Description:
        "Shows how long subscribers have been active and identifies tenure patterns.",
      Tags: ["aging", "tenure"],
      Category: ["All", "Subscriber Reports"],
      RoutePath: "/reports/subscription-aging",
      IsStarred: false,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 9,
    },
    {
      Id: "6853ce5a6c39c0df640c5c0e",
      Icon: "🔮",
      Title: "Expiration Forecast Report",
      Description:
        "Predicts upcoming subscription expirations and renewal opportunities.",
      Tags: ["expiration", "forecast"],
      Category: ["All", "Revenue Reports"],
      RoutePath: "/reports/expiration-forecast",
      IsStarred: false,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 10,
    },
    {
      Id: "6853ce5a6c39c0df640c5c0f",
      Icon: "📊",
      Title: "Churn by Cohort",
      Description:
        "Analyze customer retention and churn patterns across acquisition cohorts with behavioral insights and risk assessment.",
      Tags: ["cohort", "churn"],
      Category: ["All", "Performance Reports"],
      RoutePath: "/reports/churn-cohort",
      IsStarred: false,
      IsAdmin: true,
      UserId: -1,
      ModifiedTitle: "",
      CreatedDate: "2025-06-19T08:46:18.317Z",
      ModifiedDate: null,
      IsMaster: true,
      SortOrder: 11,
    },
  ],
};
