// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://migdvtnqtkkygwydreoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pZ2R2dG5xdGtreWd3eWRyZW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTc5NjgsImV4cCI6MjA2NDM5Mzk2OH0.QU6REdwimGLMmla6xx31EChtPUPC8kyhGzecgiOgjfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});