// Default column order for the opportunities table
export const getDefaultColumnOrder = () => [
    { id: 'opportunityName', label: 'Opportunity Name' },
    { id: 'companyName', label: 'Company' },
    { id: 'contactName', label: 'Contact' },
    { id: 'assignedRep', label: 'Assigned Rep' },
    { id: 'stage', label: 'Stage' },
    { id: 'status', label: 'Status' },
    { id: 'amount', label: 'Amount' },
    { id: 'probability', label: 'Probability' },
    { id: 'projCloseDate', label: 'Proj. Close Date' },
    { id: 'actualCloseDate', label: 'Actual Close Date' },
    { id: 'createdDate', label: 'Created Date' },
    { id: 'description', label: 'Description' },
    { id: 'source', label: 'Source' },
    { id: 'opportunityType', label: 'Opportunity Type' },
    { id: 'createdBy', label: 'Created By' },
    { id: 'lastActivity', label: 'Last Activity' },
    { id: 'lastActivityDate', label: 'Last Activity Date' },
    { id: 'nextStep', label: 'Next Step' },
    { id: 'product', label: 'Product' },
    { id: 'leadStatus', label: 'Lead Status' },
    { id: 'leadSource', label: 'Lead Source' },
    { id: 'leadType', label: 'Lead Type' },
    { id: 'prospectingStage', label: 'Prospecting Stage' },
    { id: 'proposalId', label: 'Proposal ID' },
    { id: 'lossReason', label: 'Loss Reason' },
    { id: 'salesPresenter', label: 'Sales Presenter' },
    { id: 'businessUnit', label: 'Business Unit' },
    { id: 'forecastRevenue', label: 'Forecast Revenue' },
    { id: 'opportunityId', label: 'Opportunity ID' },
    { id: 'contactId', label: 'Contact ID' }
  ];