// src/config/devHelper.js
// Development-only configuration values

export const DEV_BASE_URL = 'https://smoke-feature13.magazinemanager.com/';
export const DEV_DOMAIN = 'smoke-feature13';
export const DEV_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJMb2dnZWRJblVzZXJJRCI6IjEiLCJMb2dnZWRJblNpdGVDbGllbnRJRCI6IjEwMDA3IiwiTG9nZ2VkSW5TaXRlQ3VsdHVyZVVJIjoiZW4tVVMiLCJEYXRlVGltZSI6IjcvMzAvMjAyNSAxMjo1MjozOSBQTSIsIkxvZ2dlZEluU2l0ZUN1cnJlbmN5U3ltYm9sIjoiIiwiTG9nZ2VkSW5TaXRlRGF0ZUZvcm1hdCI6IiIsIkRvbWFpbiI6InNtb2tlLWZlYXR1cmUxMyIsIkxvZ2dlZEluU2l0ZVRpbWVBZGQiOlsiMCIsIjAiXSwiU291cmNlIjoiVE1NIiwiRW1haWwiOiJzYUBtYWdhemluZW1hbmFnZXIuY29tIiwiSXNBUElVc2VyIjoiRmFsc2UiLCJuYmYiOjE3NTM4Nzk5NTksImV4cCI6MTc1Njg3OTk1OSwiaWF0IjoxNzUzODc5OTU5LCJpc3MiOiJNYWdhemluZU1hbmFnZXIiLCJhdWQiOiIqIn0.GMBn3Yj3wUbqltrbzO1vizzYb9c54G3_Ey9bm8Z0j3A'; 