// src/config/devHelper.js
// Development-only configuration values

export const DEV_BASE_URL = 'https://smoke-feature16.magazinemanager.com/';
export const DEV_DOMAIN = 'smoke-feature16';
export const DEV_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJMb2dnZWRJblVzZXJJRCI6IjEiLCJMb2dnZWRJblNpdGVDbGllbnRJRCI6IjEwMDEwIiwiTG9nZ2VkSW5TaXRlQ3VsdHVyZVVJIjoiZW4tVVMiLCJEYXRlVGltZSI6IjcvOS8yMDI1IDE6MzE6MTMgUE0iLCJMb2dnZWRJblNpdGVDdXJyZW5jeVN5bWJvbCI6IiIsIkxvZ2dlZEluU2l0ZURhdGVGb3JtYXQiOiIiLCJEb21haW4iOiJzbW9rZS1mZWF0dXJlMTYiLCJMb2dnZWRJblNpdGVUaW1lQWRkIjpbIjAiLCIwIl0sIlNvdXJjZSI6IlRNTSIsIkVtYWlsIjoic2FAbWFnYXppbmVtYW5hZ2VyLmNvbSIsIklzQVBJVXNlciI6IkZhbHNlIiwibmJmIjoxNzUyMDY3ODczLCJleHAiOjE3NTUwNjc4NzMsImlhdCI6MTc1MjA2Nzg3MywiaXNzIjoiTWFnYXppbmVNYW5hZ2VyIiwiYXVkIjoiKiJ9.__WrOaIZDXbYgCPXWRuWBKaTeqbGj0Zl8C74_Gh6UEo'; 