// src/config/devHelper.js
// Development-only configuration values

export const DEV_BASE_URL = 'https://smoke-feature16.magazinemanager.com/';
export const DEV_DOMAIN = 'smoke-feature16';
export const DEV_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJMb2dnZWRJblVzZXJJRCI6IjEiLCJMb2dnZWRJblNpdGVDbGllbnRJRCI6IjEwMDEwIiwiTG9nZ2VkSW5TaXRlQ3VsdHVyZVVJIjoiZW4tVVMiLCJEYXRlVGltZSI6IjYvMTkvMjAyNSA5OjQ2OjM0IEFNIiwiTG9nZ2VkSW5TaXRlQ3VycmVuY3lTeW1ib2wiOiIiLCJMb2dnZWRJblNpdGVEYXRlRm9ybWF0IjoiIiwiRG9tYWluIjoic21va2UtZmVhdHVyZTE2IiwiTG9nZ2VkSW5TaXRlVGltZUFkZCI6WyIwIiwiMCJdLCJTb3VyY2UiOiJUTU0iLCJFbWFpbCI6InNhQG1hZ2F6aW5lbWFuYWdlci5jb20iLCJJc0FQSVVzZXIiOiJGYWxzZSIsIm5iZiI6MTc1MDMyNjM5NCwiZXhwIjoxNzUzMzI2Mzk0LCJpYXQiOjE3NTAzMjYzOTQsImlzcyI6Ik1hZ2F6aW5lTWFuYWdlciIsImF1ZCI6IioifQ.XD2hv_SihorcCbT-7RPoLlw2ca2RteULsOCbI_Zae90'; 