
import { HelpItem } from './types';

export const revenueHelpItems: HelpItem[] = [
  {
    id: 'revenue-overview',
    instruction: 'Detailed breakdown of revenue metrics including total revenue, average revenue per user (ARPU), revenue growth rate, and customer lifetime value (LTV).',
    fieldName: 'Revenue Overview',
    page: 'Circulation Dashboard'
  },
  {
    id: 'total-revenue',
    instruction: 'Total Monthly Recurring Revenue from all active subscriptions across all subscription types. This represents the predictable monthly income from subscription fees.',
    fieldName: 'Total Revenue',
    page: 'Revenue Overview'
  },
  {
    id: 'average-revenue-per-user',
    instruction: 'Average Revenue Per User (ARPU) calculated by dividing total monthly revenue by the number of active subscribers. Shows the average monthly value per subscriber.',
    fieldName: 'Average Revenue Per User',
    page: 'Revenue Overview'
  },
  {
    id: 'revenue-growth',
    instruction: 'Monthly revenue growth rate showing the percentage increase in revenue compared to the previous month. Positive growth indicates expanding revenue.',
    fieldName: 'Revenue Growth',
    page: 'Revenue Overview'
  },
  {
    id: 'customer-ltv',
    instruction: 'Customer Lifetime Value representing the total revenue expected from a subscriber over their entire relationship with your service, based on historical data and retention patterns.',
    fieldName: 'Customer LTV',
    page: 'Revenue Overview'
  },
  {
    id: 'geographic-revenue-distribution',
    instruction: 'Breakdown of subscription revenue by geographic regions, helping identify high-value markets and expansion opportunities.',
    fieldName: 'Geographic Revenue Distribution',
    page: 'Revenue Analysis'
  },
  {
    id: 'subscription-type-revenue',
    instruction: 'Revenue analysis segmented by subscription types (print, digital, premium) showing which offerings generate the most income.',
    fieldName: 'Revenue by Subscription Type',
    page: 'Revenue Analysis'
  },
  {
    id: 'revenue-attribution',
    instruction: 'Multi-touch attribution analysis showing which marketing channels and touchpoints contribute most to subscription revenue generation.',
    fieldName: 'Revenue Attribution',
    page: 'Revenue Analysis'
  },
  // Individual revenue metric cards
  {
    id: 'revenue-total-revenue',
    instruction: 'Total Monthly Recurring Revenue from all active subscriptions across all subscription types. This represents the predictable monthly income from subscription fees.',
    fieldName: 'Total Revenue',
    page: 'Revenue Overview'
  },
  {
    id: 'revenue-monthly-recurring',
    instruction: 'Monthly Recurring Revenue (MRR) showing the normalized monthly subscription revenue with month-over-month growth percentage.',
    fieldName: 'Monthly Recurring',
    page: 'Revenue Overview'
  },
  {
    id: 'revenue-average-revenue-per-user',
    instruction: 'Average Revenue Per User (ARPU) calculated by dividing total monthly revenue by the number of active subscribers.',
    fieldName: 'Average Revenue Per User',
    page: 'Revenue Overview'
  },
  {
    id: 'revenue-revenue-per-month',
    instruction: 'Current month revenue projection based on existing subscriptions and expected new acquisitions.',
    fieldName: 'Revenue Per Month',
    page: 'Revenue Overview'
  },
  // Attribution components
  {
    id: 'channel-type-matrix',
    instruction: 'Revenue attribution breakdown showing how different acquisition channels and subscription types contribute to total revenue.',
    fieldName: 'Attribution by Channel & Type',
    page: 'Revenue Attribution'
  },
  {
    id: 'geographic-attribution',
    instruction: 'Revenue attribution by geographic regions showing which markets drive the most subscription revenue.',
    fieldName: 'Geographic Attribution',
    page: 'Revenue Attribution'
  },
  {
    id: 'attribution-summary',
    instruction: 'Overall performance summary of the multi-touch attribution model showing total attributed revenue, model confidence, and average customer touchpoints.',
    fieldName: 'Attribution Model Summary',
    page: 'Revenue Attribution'
  },
  // Channel revenue components
  {
    id: 'acquisition-channel-revenue',
    instruction: 'Bar chart showing total revenue generated by each customer acquisition channel, helping identify which marketing channels drive the most subscription revenue.',
    fieldName: 'Revenue by Acquisition Channel',
    page: 'Channel Revenue'
  },
  {
    id: 'channel-revenue-distribution',
    instruction: 'Pie chart visualization showing the percentage breakdown of total revenue contributed by each acquisition channel.',
    fieldName: 'Channel Revenue Distribution',
    page: 'Channel Revenue'
  },
  {
    id: 'channel-performance-metrics',
    instruction: 'Comprehensive performance table showing key metrics for each acquisition channel including revenue, subscriber count, ARPU, and LTV/CAC ratio.',
    fieldName: 'Channel Performance Metrics',
    page: 'Channel Revenue'
  },
  // Subscription type revenue
  {
    id: 'revenue-trends-subscription-type',
    instruction: 'Stacked area chart showing revenue trends over time for each subscription type (print, digital, and combined subscriptions).',
    fieldName: 'Revenue Trends by Subscription Type',
    page: 'Subscription Revenue'
  },
  {
    id: 'subscription-type-performance',
    instruction: 'Comprehensive performance breakdown showing key metrics for each subscription type including revenue, subscriber count, ARPU, and growth rate.',
    fieldName: 'Subscription Type Performance',
    page: 'Subscription Revenue'
  },
  // Geographic revenue
  {
    id: 'top-revenue-cities',
    instruction: 'Ranked list of cities generating the highest subscription revenue with subscriber counts and revenue totals.',
    fieldName: 'Top Revenue Cities',
    page: 'Geographic Revenue'
  },
  {
    id: 'regional-performance-metrics',
    instruction: 'Regional performance analysis showing revenue, ARPU, and growth metrics by geographic region.',
    fieldName: 'Regional Performance Metrics',
    page: 'Geographic Revenue'
  }
];
