// Initial sales data for the application
export const initialSalesData = [
  {
    id: 1,
    customer: 'John Doe',
    email: 'john@example.com',
    product: 'Premium Package',
    amount: 1200,
    status: 'Completed',
    date: '2023-04-15',
  },
  {
    id: 2,
    customer: 'Sarah Wilson',
    email: 'sarah@example.com',
    product: 'Basic Subscription',
    amount: 450,
    status: 'Pending',
    date: '2023-04-18',
  },
  {
    id: 3,
    customer: 'Michael Brown',
    email: 'michael@example.com',
    product: 'Enterprise Solution',
    amount: 3500,
    status: 'Completed',
    date: '2023-04-10',
  },
  {
    id: 4,
    customer: 'Emily Davis',
    email: 'emily@example.com',
    product: 'Consulting Services',
    amount: 850,
    status: 'Cancelled',
    date: '2023-04-05',
  },
  {
    id: 5,
    customer: 'Robert Johnson',
    email: 'robert@example.com',
    product: 'Premium Package',
    amount: 1200,
    status: 'Pending',
    date: '2023-04-20',
  },
];